### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by jennsuzhoy** [moderntribe/tribe-storage#24]
Hey team - both the PHP version and Flysystem adapter on the most recent release are outdated. Is there a new version in the works to address this issue?

**Comment by defunctl** [comment]
Hey @jennsuzhoy this likely just needs some composer.json changes, did you find another solution or why was this closed?

**Comment by defunctl** [comment]
Version 3.0.1+ now supports PHP7.4-8.2: https://github.com/moderntribe/tribe-storage/releases
